class Country{
  String fullName;
  String shortName;
  Country(this.shortName, this.fullName);
  @override
  String toString() {
    return '{ ${this.fullName}, ${this.shortName} }';
  }
}
List<Country> countries = [
  Country('🇦🇨','Ascension Island'),
  Country('🇦🇩','Andorra'),
  Country('🇦🇪','United Arab Emirates'),
  Country('🇦🇫','Afghanistan'),
  Country('🇦🇬','Antigua & Barbuda'),
  Country('🇦🇮','Anguilla'),
  Country('🇦🇱','Albania'),
  Country('🇦🇲','Armenia'),
  Country('🇦🇴','Angola'),
  Country('🇦🇶','Antarctica'),
  Country('🇦🇷','Argentina'),
  Country('🇦🇸','American Samoa'),
  Country('🇦🇹','Austria'),
  Country('🇦🇺','Australia'),
  Country('🇦🇼','Aruba'),
  Country('🇦🇽','Åland Islands'),
  Country('🇦🇿','Azerbaijan'),
  Country('🇧🇦','Bosnia And Herzegovina'),
  Country('🇧🇧','Barbados'),
  Country('🇧🇩','Bangladesh'),
  Country('🇧🇪','Belgium'),
  Country('🇧🇫','Burkina Faso'),
  Country('🇧🇬','Bulgaria'),
  Country('🇧🇭','Bahrain'),
  Country('🇧🇮','Burundi'),
  Country('🇧🇯','Benin'),
  Country('🇧🇱','St. Barthélemy'),
  Country('🇧🇲','Bermuda'),
  Country('🇧🇳','Brunei'),
  Country('🇧🇴','Bolivia'),
  Country('🇧🇶','Caribbean Netherlands'),
  Country('🇧🇷','Brazil'),
  Country('🇧🇸','Bahamas'),
  Country('🇧🇹','Bhutan'),
  Country('🇧🇻','Bouvet Island'),
  Country('🇧🇼','Botswana'),
  Country('🇧🇾','Belarus'),
  Country('🇧🇿','Belize'),
  Country('🇨🇦','Canada'),
  Country('🇨🇨','Cocos (Keeling) Islands'),
  Country('🇨🇩','Democratic Republic Of The Congo'),
  Country('🇨🇫','Central African Republic'),
  Country('🇨🇬','Republic of Congo'),
  Country('🇨🇭','Switzerland'),
  Country('🇨🇮','Côte d’Ivoire'),
  Country('🇨🇰','Cook Islands'),
  Country('🇨🇱','Chile'),
  Country('🇨🇲','Cameroon'),
  Country('🇨🇳','China'),
  Country('🇨🇴','Colombia'),
  Country('🇨🇵','Clipperton Island'),
  Country('🇨🇷','Costa Rica'),
  Country('🇨🇺','Cuba'),
  Country('🇨🇻','Cape Verde'),
  Country('🇨🇼','Curaçao'),
  Country('🇨🇽','Christmas Island'),
  Country('🇨🇾','Cyprus'),
  Country('🇨🇿','Czech Republic'),
  Country('🇩🇪','Germany'),
  Country('🇩🇬','Diego Garcia'),
  Country('🇩🇯','Djibouti'),
  Country('🇩🇰','Denmark'),
  Country('🇩🇲','Dominica'),
  Country('🇩🇴','Dominican Republic'),
  Country('🇩🇿','Algeria'),
  Country('🇪🇦','Ceuta & Melilla'),
  Country('🇪🇨','Ecuador'),
  Country('🇪🇪','Estonia'),
  Country('🇪🇬','Egypt'),
  Country('🇪🇭','Western Sahara'),
  Country('🇪🇷','Eritrea'),
  Country('🇪🇸','Spain'),
  Country('🇪🇹','Ethiopia'),
  Country('🇪🇺','European Union'),
  Country('🇫🇮','Finland'),
  Country('🇫🇯','Fiji'),
  Country('🇫🇰','Falkland Islands'),
  Country('🇫🇲','Micronesia'),
  Country('🇫🇴','Faroe Islands'),
  Country('🇫🇷','France'),
  Country('🇬🇦','Gabon'),
  Country('🇬🇧','United Kingdom'),
  Country('🇬🇩','Grenada'),
  Country('🇬🇪','Georgia'),
  Country('🇬🇫','French Guiana'),
  Country('🇬🇬','Guernsey'),
  Country('🇬🇭','Ghana'),
  Country('🇬🇮','Gibraltar'),
  Country('🇬🇱','Greenland'),
  Country('🇬🇲','Gambia'),
  Country('🇬🇳','Guinea'),
  Country('🇬🇵','Guadeloupe'),
  Country('🇬🇶','Equatorial Guinea'),
  Country('🇬🇷','Greece'),
  Country('🇬🇸','South Georgia & South Sandwich Islands'),
  Country('🇬🇹','Guatemala'),
  Country('🇬🇺','Guam'),
  Country('🇬🇼','Guinea-Bissau'),
  Country('🇬🇾','Guyana'),
  Country('🇭🇰','Hong Kong SAR China'),
  Country('🇭🇲','Heard & McDonald Islands'),
  Country('🇭🇳','Honduras'),
  Country('🇭🇷','Croatia'),
  Country('🇭🇹','Haiti'),
  Country('🇭🇺','Hungary'),
  Country('🇮🇨','Canary Islands'),
  Country('🇮🇩','Indonesia'),
  Country('🇮🇪','Ireland'),
  Country('🇮🇱','Israel'),
  Country('🇮🇲','Isle of Man'),
  Country('🇮🇳','India'),
  Country('🇮🇴','British Indian Ocean Territory'),
  Country('🇮🇶','Iraq'),
  Country('🇮🇷','Iran'),
  Country('🇮🇸','Iceland'),
  Country('🇮🇹','Italy'),
  Country('🇯🇪','Jersey'),
  Country('🇯🇲','Jamaica'),
  Country('🇯🇴','Jordan'),
  Country('🇯🇵','Japan'),
  Country('🇰🇪','Kenya'),
  Country('🇰🇬','Kyrgyzstan'),
  Country('🇰🇭','Cambodia'),
  Country('🇰🇮','Kiribati'),
  Country('🇰🇲','Comoros'),
  Country('🇰🇳','St. Kitts & Nevis'),
  Country('🇰🇵','North Korea'),
  Country('🇰🇷','South Korea'),
  Country('🇰🇼','Kuwait'),
  Country('🇰🇾','Cayman Islands'),
  Country('🇰🇿','Kazakhstan'),
  Country('🇱🇦','Laos'),
  Country('🇱🇧','Lebanon'),
  Country('🇱🇨','St. Lucia'),
  Country('🇱🇮','Liechtenstein'),
  Country('🇱🇰','Sri Lanka'),
  Country('🇱🇷','Liberia'),
  Country('🇱🇸','Lesotho'),
  Country('🇱🇹','Lithuania'),
  Country('🇱🇺','Luxembourg'),
  Country('🇱🇻','Latvia'),
  Country('🇱🇾','Libya'),
  Country('🇲🇦','Morocco'),
  Country('🇲🇨','Monaco'),
  Country('🇲🇩','Moldova'),
  Country('🇲🇪','Montenegro'),
  Country('🇲🇫','St. Martin'),
  Country('🇲🇬','Madagascar'),
  Country('🇲🇭','Marshall Islands'),
  Country('🇲🇰','North Macedonia'),
  Country('🇲🇱','Mali'),
  Country('🇲🇲','Myanmar (Burma)'),
  Country('🇲🇳','Mongolia'),
  Country('🇲🇴','Macao SAR China'),
  Country('🇲🇵','Northern Mariana Islands'),
  Country('🇲🇶','Martinique'),
  Country('🇲🇷','Mauritania'),
  Country('🇲🇸','Montserrat'),
  Country('🇲🇹','Malta'),
  Country('🇲🇺','Mauritius'),
  Country('🇲🇻','Maldives'),
  Country('🇲🇼','Malawi'),
  Country('🇲🇽','Mexico'),
  Country('🇲🇾','Malaysia'),
  Country('🇲🇿','Mozambique'),
  Country('🇳🇦','Namibia'),
  Country('🇳🇨','New Caledonia'),
  Country('🇳🇪','Niger'),
  Country('🇳🇫','Norfolk Island'),
  Country('🇳🇬','Nigeria'),
  Country('🇳🇮','Nicaragua'),
  Country('🇳🇱','Netherlands'),
  Country('🇳🇴','Norway'),
  Country('🇳🇵','Nepal'),
  Country('🇳🇷','Nauru'),
  Country('🇳🇺','Niue'),
  Country('🇳🇿','New Zealand'),
  Country('🇴🇲','Oman'),
  Country('🇵🇦','Panama'),
  Country('🇵🇪','Peru'),
  Country('🇵🇫','French Polynesia'),
  Country('🇵🇬','Papua New Guinea'),
  Country('🇵🇭','Philippines'),
  Country('🇵🇰','Pakistan'),
  Country('🇵🇱','Poland'),
  Country('🇵🇲','St. Pierre & Miquelon'),
  Country('🇵🇳','Pitcairn Islands'),
  Country('🇵🇷','Puerto Rico'),
  Country('🇵🇸','Palestinian Territories'),
  Country('🇵🇹','Portugal'),
  Country('🇵🇼','Palau'),
  Country('🇵🇾','Paraguay'),
  Country('🇶🇦','Qatar'),
  Country('🇷🇪','Réunion'),
  Country('🇷🇴','Romania'),
  Country('🇷🇸','Serbia'),
  Country('🇷🇺','Russia'),
  Country('🇷🇼','Rwanda'),
  Country('🇸🇦','Saudi Arabia'),
  Country('🇸🇧','Solomon Islands'),
  Country('🇸🇨','Seychelles'),
  Country('🇸🇩','Sudan'),
  Country('🇸🇪','Sweden'),
  Country('🇸🇬','Singapore'),
  Country('🇸🇭','St. Helena'),
  Country('🇸🇮','Slovenia'),
  Country('🇸🇯','Svalbard & Jan Mayen'),
  Country('🇸🇰','Slovakia'),
  Country('🇸🇱','Sierra Leone'),
  Country('🇸🇲','San Marino'),
  Country('🇸🇳','Senegal'),
  Country('🇸🇴','Somalia'),
  Country('🇸🇷','Suriname'),
  Country('🇸🇸','South Sudan'),
  Country('🇸🇹','São Tomé & Príncipe'),
  Country('🇸🇻','El Salvador'),
  Country('🇸🇽','Sint Maarten'),
  Country('🇸🇾','Syria'),
  Country('🇸🇿','Eswatini'),
  Country('🇹🇦','Tristan da Cunha'),
  Country('🇹🇨','Turks & Caicos Islands'),
  Country('🇹🇩','Chad'),
  Country('🇹🇫','French Southern Territories'),
  Country('🇹🇬','Togo'),
  Country('🇹🇭','Thailand'),
  Country('🇹🇯','Tajikistan'),
  Country('🇹🇰','Tokelau'),
  Country('🇹🇱','Timor-Leste'),
  Country('🇹🇲','Turkmenistan'),
  Country('🇹🇳','Tunisia'),
  Country('🇹🇴','Tonga'),
  Country('🇹🇷','Turkey'),
  Country('🇹🇹','Trinidad & Tobago'),
  Country('🇹🇻','Tuvalu'),
  Country('🇹🇼','Taiwan'),
  Country('🇹🇿','Tanzania'),
  Country('🇺🇦','Ukraine'),
  Country('🇺🇬','Uganda'),
  Country('🇺🇲','U.S. Outlying Islands'),
  Country('🇺🇳','United Nations'),
  Country('🇺🇸','United States'),
  Country('🇺🇾','Uruguay'),
  Country('🇺🇿','Uzbekistan'),
  Country('🇻🇦','Vatican City'),
  Country('🇻🇨','St. Vincent & Grenadines'),
  Country('🇻🇪','Venezuela'),
  Country('🇻🇬','British Virgin Islands'),
  Country('🇻🇮','U.S. Virgin Islands'),
  Country('🇻🇳','Vietnam'),
  Country('🇻🇺','Vanuatu'),
  Country('🇼🇫','Wallis & Futuna'),
  Country('🇼🇸','Samoa'),
  Country('🇽🇰','Kosovo'),
  Country('🇾🇪','Yemen'),
  Country('🇾🇹','Mayotte'),
  Country('🇿🇦','South Africa'),
  Country('🇿🇲','Zambia'),
  Country('🇿🇼','Zimbabwe')
];
